# kubectl create secret generic -n metallb-system memberlist --from-literal=secretkey="$(openssl rand -base64 128)"
apiVersion: v1
data:
  secretkey: SzdkMW9lbFRMbnFHc1J6SlFIVHJCM3FDQU5qU0Rock1hV01YaG9PYm84RHorNGxKbXMvWDhWTW9zemI1WXRUVwo3R1NKTVlaT0ZucjY1dGErUVBpQzB5ZXVSZGNpRUFCeDkrV1J3eXVoQUlqcUlVTDhZVTRLR215VWwzcEtnaDgyCmxTb2RMallNNDRoeTVJTENTNVZtODlQcDZJZ3Jwb003bU5hWG84cnhzNnc9
kind: Secret
metadata:
  name: memberlist
  namespace: metallb-system
